spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/magalu
    driverClassName: org.postgresql.Driver
    username: postgres
    password: leo123
  jpa:
    database-platform: POSTGRESQL
    show-sql: true
    properties:
      hibernate:
        ddl-auto: create-drop
      format_sql: true

#logging:
#  level:
#    br:
#      com:
#        leonardo: DEBUG